/** Dog breeds — English (FCI) + Georgian labels. */
export interface DogBreed { en: string; ka: string; }

export const DOG_BREEDS: DogBreed[] = [
  { en: "Afghan Hound", ka: "ავღანური ბრწყინვალე" },
  { en: "Airedale Terrier", ka: "ერდეილის ტერიერი" },
  { en: "Akita", ka: "აკიტა" },
  { en: "Alaskan Malamute", ka: "ალასკის მალამუტი" },
  { en: "American Akita", ka: "ამერიკული აკიტა" },
  { en: "American Bully", ka: "ამერიკული ბული" },
  { en: "American Cocker Spaniel", ka: "ამერიკული კოკერ-სპანიელი" },
  { en: "American English Coonhound", ka: "ამერიკული ინგლისური კუნჰაუნდი" },
  { en: "American Foxhound", ka: "ამერიკული ფოქსჰაუნდი" },
  { en: "American Hairless Terrier", ka: "ამერიკული უთმოსი ტერიერი" },
  { en: "American Staffordshire Terrier", ka: "ამერიკული სტაფორდშირის ტერიერი" },
  { en: "American Water Spaniel", ka: "ამერიკული წყლის სპანიელი" },
  { en: "Anatolian Shepherd Dog", ka: "ანატოლიის ნაგაზი" },
  { en: "Appenzeller Sennenhund", ka: "აპპენზელლერ სენნენჰუნდ" },
  { en: "Argentine Dogo", ka: "არგენტინე დოგო" },
  { en: "Ariege Pointer", ka: "არიეგე პოინტერ" },
  { en: "Ariegeois", ka: "არიეგეოის" },
  { en: "Artois Hound", ka: "არტოის ჰოუნდ" },
  { en: "Australian Cattle Dog", ka: "ავსტრალიული საქონლის ძაღლი" },
  { en: "Australian Kelpie", ka: "აუსტრალიან კელპიე" },
  { en: "Australian Shepherd", ka: "აუსტრალიან სჰეპჰერდ" },
  { en: "Australian Silky Terrier", ka: "აუსტრალიან სილკი ტერრიერ" },
  { en: "Australian Stumpy Tail Cattle Dog", ka: "აუსტრალიან სტუმპი ტაილ კატტლე დოგ" },
  { en: "Australian Terrier", ka: "ავსტრალიული ტერიერი" },
  { en: "Austrian Black and Tan Hound", ka: "აუსტრიან ბლაკკ ანდ ტან ჰოუნდ" },
  { en: "Austrian Pinscher", ka: "აუსტრიან პინსკჰერ" },
  { en: "Azawakh", ka: "აზავაკი" },
  { en: "Barbet", ka: "ბარბეტ" },
  { en: "Basenji", ka: "ბასენჯი" },
  { en: "Basset Artesien Normand", ka: "ბასსეტ არტესიენ ნორმანდ" },
  { en: "Basset Bleu de Gascogne", ka: "ბასსეტ ბლეუ დე გასკოგნე" },
  { en: "Basset Fauve de Bretagne", ka: "ბასსეტ ფაუვე დე ბრეტაგნე" },
  { en: "Basset Hound", ka: "ბასსეტ ჰოუნდ" },
  { en: "Bavarian Mountain Scent Hound", ka: "ბავარიან მოუნტაინ სკენტ ჰოუნდ" },
  { en: "Beagle", ka: "ბიგლი" },
  { en: "Beagle-Harrier", ka: "ბიგლ-ჰარიერი" },
  { en: "Bearded Collie", ka: "ბეარდედ კოლლიე" },
  { en: "Beauceron", ka: "ბეაუკერონ" },
  { en: "Bedlington Terrier", ka: "ბედლინგტონ ტერრიერ" },
  { en: "Belgian Shepherd Dog Groenendael", ka: "ბელგიან სჰეპჰერდ დოგ გროენენდაელ" },
  { en: "Belgian Shepherd Dog Laekenois", ka: "ბელგიან სჰეპჰერდ დოგ ლაეკენოის" },
  { en: "Belgian Shepherd Dog Malinois", ka: "ბელგიან სჰეპჰერდ დოგ მალინოის" },
  { en: "Belgian Shepherd Dog Tervuren", ka: "ბელგიან სჰეპჰერდ დოგ ტერვურენ" },
  { en: "Bergamasco Shepherd", ka: "ბერგამასკო სჰეპჰერდ" },
  { en: "Berger Picard", ka: "ბერგერ პიკარდ" },
  { en: "Bernese Mountain Dog", ka: "ბერნესე მოუნტაინ დოგ" },
  { en: "Bichon Frise", ka: "ბიკჰონ ფრისე" },
  { en: "Billy", ka: "ბილლი" },
  { en: "Black and Tan Coonhound", ka: "ბლაკკ ანდ ტან კოონჰოუნდ" },
  { en: "Black Russian Terrier", ka: "ბლაკკ რუსსიან ტერრიერ" },
  { en: "Bloodhound", ka: "ბლოოდჰოუნდ" },
  { en: "Blue Picardy Spaniel", ka: "ბლუე პიკარდი სპანიელ" },
  { en: "Bluetick Coonhound", ka: "ბლუეტიკკ კოონჰოუნდ" },
  { en: "Boerboel", ka: "ბოერბოელ" },
  { en: "Bohemian Wire-haired Pointing Griffon", ka: "ბოჰემიან უირე-ჰაირედ პოინტინგ გრიფფონ" },
  { en: "Bolognese", ka: "ბოლოგნესე" },
  { en: "Border Collie", ka: "ბორდერ კოლი" },
  { en: "Border Terrier", ka: "ბორდერ ტერრიერ" },
  { en: "Borzoi", ka: "ბორზოი" },
  { en: "Boston Terrier", ka: "ბოსტონ ტერრიერ" },
  { en: "Bouvier des Ardennes", ka: "ბოუვიერ დეს არდენნეს" },
  { en: "Bouvier des Flandres", ka: "ბოუვიერ დეს ფლანდრეს" },
  { en: "Boxer", ka: "ბოქსერი" },
  { en: "Boykin Spaniel", ka: "ბოიკინ სპანიელ" },
  { en: "Bracco Italiano", ka: "ბრაკკო იტალიანო" },
  { en: "Braque d'Auvergne", ka: "ბრაკუე დაუვერგნე" },
  { en: "Braque du Bourbonnais", ka: "ბრაკუე დუ ბოურბონნაის" },
  { en: "Braque Francais", ka: "ბრაკუე ფრანკაის" },
  { en: "Braque Saint-Germain", ka: "ბრაკუე საინტ-გერმაინ" },
  { en: "Briard", ka: "ბრიარდ" },
  { en: "Briquet Griffon Vendeen", ka: "ბრიკუეტ გრიფფონ ვენდეენ" },
  { en: "Brittany", ka: "ბრიტტანი" },
  { en: "Broholmer", ka: "ბროჰოლმერ" },
  { en: "Bull Terrier", ka: "ბულ ტერიერი" },
  { en: "Bulldog", ka: "ბულდოგი" },
  { en: "Bullmastiff", ka: "ბულლმასტიფფ" },
  { en: "Cairn Terrier", ka: "კაირნ ტერრიერ" },
  { en: "Canaan Dog", ka: "კანაან დოგ" },
  { en: "Canadian Eskimo Dog", ka: "კანადიან ესკიმო დოგ" },
  { en: "Cane Corso", ka: "კანე კორსო" },
  { en: "Caucasian Shepherd Dog", ka: "კავკასიური ნაგაზი" },
  { en: "Cavalier King Charles Spaniel", ka: "კავალიერ კინგ კჰარლეს სპანიელ" },
  { en: "Central Asian Shepherd Dog", ka: "ცენტრალურაზიის ნაგაზი" },
  { en: "Cesky Fousek", ka: "კესკი ფოუსეკ" },
  { en: "Cesky Terrier", ka: "კესკი ტერრიერ" },
  { en: "Chesapeake Bay Retriever", ka: "კჰესაპეაკე ბაი რეტრიევერ" },
  { en: "Chihuahua", ka: "ჩიხუახუა" },
  { en: "Chinese Crested Dog", ka: "კჰინესე კრესტედ დოგ" },
  { en: "Chinook", ka: "კჰინოოკ" },
  { en: "Chow Chow", ka: "ჩაუ-ჩაუ" },
  { en: "Cirneco dell'Etna", ka: "კირნეკო დელლეტნა" },
  { en: "Clumber Spaniel", ka: "კლუმბერ სპანიელ" },
  { en: "Coarse-haired Hound", ka: "კოარსე-ჰაირედ ჰოუნდ" },
  { en: "Cocker Spaniel", ka: "კოკერ-სპანიელი" },
  { en: "Collie Rough", ka: "კოლლიე როუგჰ" },
  { en: "Collie Smooth", ka: "კოლლიე სმოოტჰ" },
  { en: "Coton de Tulear", ka: "კოტონ დე ტულეარ" },
  { en: "Curly Coated Retriever", ka: "კურლი კოატედ რეტრიევერ" },
  { en: "Czechoslovakian Vlcak", ka: "კზეკჰოსლოვაკიან ვლკაკ" },
  { en: "Dachshund", ka: "მალიაშის ძაღლი" },
  { en: "Dalmatian", ka: "დალმატიან" },
  { en: "Dandie Dinmont Terrier", ka: "დანდიე დინმონტ ტერრიერ" },
  { en: "Danish-Swedish Farmdog", ka: "დანისჰ-სუედისჰ ფარმდოგ" },
  { en: "Dobermann", ka: "დობერმანი" },
  { en: "Dogo Argentino", ka: "დოგო არგენტინო" },
  { en: "Dogue de Bordeaux", ka: "დოგუე დე ბორდეაუქს" },
  { en: "Drentsche Patrijshond", ka: "დრენტსკჰე პატრიჯსჰონდ" },
  { en: "Drever", ka: "დრევერ" },
  { en: "Dutch Shepherd Dog", ka: "დუტკჰ სჰეპჰერდ დოგ" },
  { en: "English Cocker Spaniel", ka: "ინგლისური კოკერ-სპანიელი" },
  { en: "English Foxhound", ka: "ინგლისური ფოქსჰაუნდი" },
  { en: "English Mastiff", ka: "ენგლისჰ მასტიფფ" },
  { en: "English Pointer", ka: "ინგლისური პოინტერი" },
  { en: "English Setter", ka: "ინგლისური სეტერი" },
  { en: "English Springer Spaniel", ka: "ენგლისჰ სპრინგერ სპანიელ" },
  { en: "English Toy Terrier", ka: "ენგლისჰ ტოი ტერრიერ" },
  { en: "Entlebucher Mountain Dog", ka: "ენტლებუკჰერ მოუნტაინ დოგ" },
  { en: "Eurasier", ka: "ეურასიერ" },
  { en: "Field Spaniel", ka: "ფიელდ სპანიელ" },
  { en: "Fila Brasileiro", ka: "ფილა ბრასილეირო" },
  { en: "Finnish Hound", ka: "ფინნისჰ ჰოუნდ" },
  { en: "Finnish Lapphund", ka: "ფინნისჰ ლაპპჰუნდ" },
  { en: "Finnish Spitz", ka: "ფინნისჰ სპიტზ" },
  { en: "Flat Coated Retriever", ka: "ფლატ კოატედ რეტრიევერ" },
  { en: "French Bulldog", ka: "ფრანღული ბულდოგი" },
  { en: "French Spaniel", ka: "ფრენკჰ სპანიელ" },
  { en: "German Pinscher", ka: "გერმან პინსკჰერ" },
  { en: "German Rough-haired Pointer", ka: "გერმან როუგჰ-ჰაირედ პოინტერ" },
  { en: "German Shepherd Dog", ka: "გერმანული ნაგაზი" },
  { en: "German Short-haired Pointing Dog", ka: "გერმან სჰორტ-ჰაირედ პოინტინგ დოგ" },
  { en: "German Spaniel", ka: "გერმან სპანიელ" },
  { en: "German Spitz", ka: "გერმან სპიტზ" },
  { en: "German Wire-haired Pointing Dog", ka: "გერმან უირე-ჰაირედ პოინტინგ დოგ" },
  { en: "Giant Schnauzer", ka: "გიანტ სკჰნაუზერ" },
  { en: "Glen of Imaal Terrier", ka: "გლენ ოფ იმაალ ტერრიერ" },
  { en: "Golden Retriever", ka: "გოლდენ რეტრივერი" },
  { en: "Gordon Setter", ka: "გორდონ სეტტერ" },
  { en: "Grand Basset Griffon Vendeen", ka: "გრანდ ბასსეტ გრიფფონ ვენდეენ" },
  { en: "Grand Bleu de Gascogne", ka: "გრანდ ბლეუ დე გასკოგნე" },
  { en: "Great Dane", ka: "გრეატ დანე" },
  { en: "Great Pyrenees", ka: "გრეატ პირენეეს" },
  { en: "Greater Swiss Mountain Dog", ka: "გრეატერ სუისს მოუნტაინ დოგ" },
  { en: "Greenland Dog", ka: "გრეენლანდ დოგ" },
  { en: "Greyhound", ka: "გრეიჰოუნდ" },
  { en: "Griffon Bruxellois", ka: "გრიფფონ ბრუქსელლოის" },
  { en: "Hamiltonstovare", ka: "ჰამილტონსტოვარე" },
  { en: "Hanoverian Scent Hound", ka: "ჰანოვერიან სკენტ ჰოუნდ" },
  { en: "Harrier", ka: "ჰარრიერ" },
  { en: "Havanese", ka: "ჰავანესე" },
  { en: "Hokkaido", ka: "ჰოკკაიდო" },
  { en: "Hovawart", ka: "ჰოვაუარტ" },
  { en: "Hungarian Greyhound", ka: "ჰუნგარიან გრეიჰოუნდ" },
  { en: "Hungarian Hound", ka: "ჰუნგარიან ჰოუნდ" },
  { en: "Hungarian Kuvasz", ka: "ჰუნგარიან კუვასზ" },
  { en: "Hungarian Puli", ka: "ჰუნგარიან პული" },
  { en: "Hungarian Pumi", ka: "ჰუნგარიან პუმი" },
  { en: "Hungarian Short-haired Pointer", ka: "ჰუნგარიან სჰორტ-ჰაირედ პოინტერ" },
  { en: "Hungarian Vizsla", ka: "ჰუნგარიან ვიზსლა" },
  { en: "Hungarian Wire-haired Pointer", ka: "ჰუნგარიან უირე-ჰაირედ პოინტერ" },
  { en: "Ibizan Hound", ka: "იბიზან ჰოუნდ" },
  { en: "Icelandic Sheepdog", ka: "იკელანდიკ სჰეეპდოგ" },
  { en: "Irish Red and White Setter", ka: "ირისჰ რედ ანდ უჰიტე სეტტერ" },
  { en: "Irish Setter", ka: "ირისჰ სეტტერ" },
  { en: "Irish Terrier", ka: "ირისჰ ტერრიერ" },
  { en: "Irish Water Spaniel", ka: "ირისჰ უატერ სპანიელ" },
  { en: "Irish Wolfhound", ka: "ირისჰ უოლფჰოუნდ" },
  { en: "Italian Greyhound", ka: "იტალიან გრეიჰოუნდ" },
  { en: "Italian Spinone", ka: "იტალიან სპინონე" },
  { en: "Jack Russell Terrier", ka: "ჯაკკ რუსსელლ ტერრიერ" },
  { en: "Japanese Chin", ka: "ჯაპანესე კჰინ" },
  { en: "Japanese Spitz", ka: "ჯაპანესე სპიტზ" },
  { en: "Kai Ken", ka: "კაი კენ" },
  { en: "Kangal Shepherd Dog", ka: "კანგალ სჰეპჰერდ დოგ" },
  { en: "Karelian Bear Dog", ka: "კარელიან ბეარ დოგ" },
  { en: "Karst Shepherd Dog", ka: "კარსტ სჰეპჰერდ დოგ" },
  { en: "Keeshond", ka: "კეესჰონდ" },
  { en: "Kerry Blue Terrier", ka: "კერრი ბლუე ტერრიერ" },
  { en: "King Charles Spaniel", ka: "კინგ კჰარლეს სპანიელ" },
  { en: "Kishu", ka: "კისჰუ" },
  { en: "Komondor", ka: "კომონდორ" },
  { en: "Kooikerhondje", ka: "კოოიკერჰონდჯე" },
  { en: "Kromfohrlander", ka: "კრომფოჰრლანდერ" },
  { en: "Kuvasz", ka: "კუვასზ" },
  { en: "Labrador Retriever", ka: "ლაბრადორი" },
  { en: "Lagotto Romagnolo", ka: "ლაგოტტო რომაგნოლო" },
  { en: "Lakeland Terrier", ka: "ლაკელანდ ტერრიერ" },
  { en: "Lancashire Heeler", ka: "ლანკასჰირე ჰეელერ" },
  { en: "Landseer", ka: "ლანდსეერ" },
  { en: "Lapponian Herder", ka: "ლაპპონიან ჰერდერ" },
  { en: "Leonberger", ka: "ლეონბერგერ" },
  { en: "Lhasa Apso", ka: "ლჰასა აპსო" },
  { en: "Lowchen", ka: "ლოუკჰენ" },
  { en: "Maltese", ka: "მალტესე" },
  { en: "Manchester Terrier", ka: "მანკჰესტერ ტერრიერ" },
  { en: "Maremma Sheepdog", ka: "მარემმა სჰეეპდოგ" },
  { en: "Miniature Bull Terrier", ka: "მინიატურე ბულლ ტერრიერ" },
  { en: "Miniature Pinscher", ka: "მინიატურე პინსკჰერ" },
  { en: "Miniature Schnauzer", ka: "მინიატურე სკჰნაუზერ" },
  { en: "Neapolitan Mastiff", ka: "ნეაპოლიტან მასტიფფ" },
  { en: "Nederlandse Kooikerhondje", ka: "ნედერლანდსე კოოიკერჰონდჯე" },
  { en: "Newfoundland", ka: "ნეუფოუნდლანდ" },
  { en: "Norfolk Terrier", ka: "ნორფოლკ ტერრიერ" },
  { en: "Norrbottenspets", ka: "ნორრბოტტენსპეტს" },
  { en: "Norwegian Elkhound", ka: "ნორუეგიან ელკჰოუნდ" },
  { en: "Norwegian Lundehund", ka: "ნორუეგიან ლუნდეჰუნდ" },
  { en: "Norwich Terrier", ka: "ნორუიკჰ ტერრიერ" },
  { en: "Nova Scotia Duck Tolling Retriever", ka: "ნოვა სკოტია დუკკ ტოლლინგ რეტრიევერ" },
  { en: "Old English Sheepdog", ka: "ოლდ ენგლისჰ სჰეეპდოგ" },
  { en: "Otterhound", ka: "ოტტერჰოუნდ" },
  { en: "Papillon", ka: "პაპილლონ" },
  { en: "Parson Russell Terrier", ka: "პარსონ რუსსელლ ტერრიერ" },
  { en: "Pekingese", ka: "პეკინგესე" },
  { en: "Pembroke Welsh Corgi", ka: "პემბროკე უელსჰ კორგი" },
  { en: "Perro de Presa Canario", ka: "პერრო დე პრესა კანარიო" },
  { en: "Peruvian Hairless Dog", ka: "პერუვიან ჰაირლესს დოგ" },
  { en: "Pharaoh Hound", ka: "პჰარაოჰ ჰოუნდ" },
  { en: "Picardy Spaniel", ka: "პიკარდი სპანიელ" },
  { en: "Pointer", ka: "პოინტერ" },
  { en: "Polish Greyhound", ka: "პოლისჰ გრეიჰოუნდ" },
  { en: "Polish Hound", ka: "პოლისჰ ჰოუნდ" },
  { en: "Polish Lowland Sheepdog", ka: "პოლისჰ ლოულანდ სჰეეპდოგ" },
  { en: "Polish Tatra Sheepdog", ka: "პოლისჰ ტატრა სჰეეპდოგ" },
  { en: "Pomeranian", ka: "პომერანიან" },
  { en: "Poodle Standard", ka: "სტანდარტული პუდელი" },
  { en: "Poodle Miniature", ka: "მინიატურე პუდელი" },
  { en: "Poodle Toy", ka: "თოი პუდელი" },
  { en: "Portuguese Podengo", ka: "პორტუგუესე პოდენგო" },
  { en: "Portuguese Pointer", ka: "პორტუგუესე პოინტერ" },
  { en: "Portuguese Water Dog", ka: "პორტუგუესე უატერ დოგ" },
  { en: "Posavac Hound", ka: "პოსავაკ ჰოუნდ" },
  { en: "Prague Ratter", ka: "პრაგუე რატტერ" },
  { en: "Pug", ka: "პუგ" },
  { en: "Puli", ka: "პული" },
  { en: "Pumi", ka: "პუმი" },
  { en: "Pyrenean Mastiff", ka: "პირენეან მასტიფფ" },
  { en: "Pyrenean Mountain Dog", ka: "პირენეან მოუნტაინ დოგ" },
  { en: "Pyrenean Sheepdog", ka: "პირენეან სჰეეპდოგ" },
  { en: "Rafeiro do Alentejo", ka: "რაფეირო დო ალენტეჯო" },
  { en: "Rhodesian Ridgeback", ka: "რჰოდესიან რიდგებაკკ" },
  { en: "Rottweiler", ka: "როტქსილერი" },
  { en: "Russian Toy", ka: "რუსსიან ტოი" },
  { en: "Saarloos Wolfdog", ka: "საარლოოს უოლფდოგ" },
  { en: "Saint Bernard", ka: "საინტ ბერნარდ" },
  { en: "Saluki", ka: "სალუკი" },
  { en: "Samoyed", ka: "სამოიედ" },
  { en: "Schipperke", ka: "სკჰიპპერკე" },
  { en: "Scottish Terrier", ka: "სკოტტისჰ ტერრიერ" },
  { en: "Sealyham Terrier", ka: "სეალიჰამ ტერრიერ" },
  { en: "Segugio Italiano", ka: "სეგუგიო იტალიანო" },
  { en: "Shar Pei", ka: "სჰარ პეი" },
  { en: "Shetland Sheepdog", ka: "სჰეტლანდ სჰეეპდოგ" },
  { en: "Shiba Inu", ka: "სჰიბა ინუ" },
  { en: "Shih Tzu", ka: "სჰიჰ ტზუ" },
  { en: "Shikoku", ka: "სჰიკოკუ" },
  { en: "Siberian Husky", ka: "სიბირული ჰასკი" },
  { en: "Skye Terrier", ka: "სკიე ტერრიერ" },
  { en: "Sloughi", ka: "სლოუგჰი" },
  { en: "Slovakian Chovac", ka: "სლოვაკიან კჰოვაკ" },
  { en: "Slovakian Rough-haired Pointer", ka: "სლოვაკიან როუგჰ-ჰაირედ პოინტერ" },
  { en: "Slovensky Kopov", ka: "სლოვენსკი კოპოვ" },
  { en: "Small Munsterlander", ka: "სმალლ მუნსტერლანდერ" },
  { en: "Smooth Fox Terrier", ka: "სმოოტჰ ფოქს ტერრიერ" },
  { en: "Soft Coated Wheaten Terrier", ka: "სოფტ კოატედ უჰეატენ ტერრიერ" },
  { en: "Spanish Mastiff", ka: "სპანისჰ მასტიფფ" },
  { en: "Spanish Water Dog", ka: "სპანისჰ უატერ დოგ" },
  { en: "Spinone Italiano", ka: "სპინონე იტალიანო" },
  { en: "Staffordshire Bull Terrier", ka: "სტაფფორდსჰირე ბულლ ტერრიერ" },
  { en: "Standard Schnauzer", ka: "სტანდარდ სკჰნაუზერ" },
  { en: "Sussex Spaniel", ka: "სუსსექს სპანიელ" },
  { en: "Swedish Lapphund", ka: "სუედისჰ ლაპპჰუნდ" },
  { en: "Swedish Vallhund", ka: "სუედისჰ ვალლჰუნდ" },
  { en: "Taiwan Dog", ka: "ტაიუან დოგ" },
  { en: "Tatra Shepherd Dog", ka: "ტატრა სჰეპჰერდ დოგ" },
  { en: "Thai Ridgeback", ka: "ტჰაი რიდგებაკკ" },
  { en: "Tibetan Mastiff", ka: "ტიბეტან მასტიფფ" },
  { en: "Tibetan Spaniel", ka: "ტიბეტან სპანიელ" },
  { en: "Tibetan Terrier", ka: "ტიბეტან ტერრიერ" },
  { en: "Tosa Inu", ka: "ტოსა ინუ" },
  { en: "Treeing Walker Coonhound", ka: "ტრეეინგ უალკერ კოონჰოუნდ" },
  { en: "Vizsla", ka: "ვიზსლა" },
  { en: "Weimaraner", ka: "ვაიმარანერი" },
  { en: "Welsh Corgi Cardigan", ka: "უელსჰ კორგი კარდიგან" },
  { en: "Welsh Corgi Pembroke", ka: "უელსჰ კორგი პემბროკე" },
  { en: "Welsh Springer Spaniel", ka: "უელსჰ სპრინგერ სპანიელ" },
  { en: "Welsh Terrier", ka: "უელსჰ ტერრიერ" },
  { en: "West Highland White Terrier", ka: "უესტ ჰიგჰლანდ უჰიტე ტერრიერ" },
  { en: "Whippet", ka: "უჰიპპეტ" },
  { en: "White Swiss Shepherd Dog", ka: "თეთრი შვეიცარიული ნაგაზი" },
  { en: "Wire Fox Terrier", ka: "უირე ფოქს ტერრიერ" },
  { en: "Wirehaired Pointing Griffon", ka: "უირეჰაირედ პოინტინგ გრიფფონ" },
  { en: "Xoloitzcuintli", ka: "ქსოლოიტზკუინტლი" },
  { en: "Yorkshire Terrier", ka: "იორქშირული ტერიერი" },
  { en: "Mixed Breed", ka: "მეტისი / შერეული" },
] as const;

export const MIXED_BREED_KA = "მეტისი / შერეული" as const;
export const BREED_LABELS: string[] = DOG_BREEDS.map((b) => b.ka);

export function searchDogBreeds(query: string): DogBreed[] {
  const q = query.trim().toLowerCase();
  if (!q) return [...DOG_BREEDS];
  return DOG_BREEDS.filter(
    (b) => b.ka.toLowerCase().includes(q) || b.en.toLowerCase().includes(q),
  );
}

export function getBreedKa(en: string): string | undefined {
  const normalized = en.trim().toLowerCase();
  return DOG_BREEDS.find((b) => b.en.toLowerCase() === normalized)?.ka;
}

const POPULAR_BREED_EN = [
  "Cane Corso",
  "Pekingese",
  "Labrador Retriever",
  "German Shepherd Dog",
  "Golden Retriever",
  "French Bulldog",
  "Poodle Standard",
  "Border Collie",
  "Chihuahua",
  "Siberian Husky",
  "Rottweiler",
  "Beagle",
  "Yorkshire Terrier",
  "Dachshund",
  "Caucasian Shepherd Dog",
] as const;

/** Common breeds for datalist / onboarding autocomplete (Georgian labels). */
export const POPULAR_BREED_SUGGESTIONS: readonly string[] = [
  ...POPULAR_BREED_EN.map((en) => getBreedKa(en) ?? en),
  MIXED_BREED_KA,
];
